FROM ubuntu:20.04
LABEL Author="Abin Thomas <athomas@fbk.eu>"
ENV PYTHONUNBUFFERED=1
RUN apt update -y && apt upgrade -y  \
    python3-pip wget unzip
RUN pip3 install python-qpid-proton tornado
RUN wget https://github.com/Nibamot/local-manager/archive/master.zip
RUN unzip master.zip
RUN rm master.zip
RUN mv local-manager-master/local_manager_1.py .
RUN rm -rf local-manager-master/
CMD python3 local_manager_1.py